export const APP_SET_STATE = 'APP_SET_STATE'
export const APP_SET_DEVICE = 'APP_SET_DEVICE'
export const ORDER_AGAIN = 'ORDER_AGAIN'
export const SET_DATE = 'SET_DATE'
export const SET_TIME = 'SET_TIME'
// export const  = ''